parameters:
#    drassuom_location.example.class: Drassuom\LocationBundle\Example

services:
#    drassuom_location.example:
#        class: %drassuom_location.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
