parameters:
    drassuom_import.manager.class: Drassuom\ImportBundle\Manager\ImportManager
    drassuom_import.registry_manager.class: Drassuom\ImportBundle\Manager\RegistryManager
    drassuom_import.encoding.converter.class: Drassuom\ImportBundle\Encoding\FileEncodingManager

services:
    drassuom_import.manager:
        class: %drassuom_import.manager.class%
        arguments:
            - @service_container
            - @doctrine.orm.entity_manager
            - @drassuom_import.encoding.converter
            - @logger
            - @translator
            - %drassuom_import.config%
            - @drassuom_import.progress.manager

    drassuom_import.registry_manager:
        class: %drassuom_import.registry_manager.class%

    drassuom_import.encoding.converter:
        class: %drassuom_import.encoding.converter.class%
        arguments:
            - @logger
            - %drassuom_import.config.reencoding_path%